### ISSUE TITLE
Cannot view/change my organization

### ISSUE THREAD

**Issue by phileas74** [camunda-cloud/bugs#6]
As described in the docs* I'm trying to view/change my organization by the link "<my_name> Organzations" in the avatar menu.
\* see chapter "Rights concept" at https://docs.cloud.camunda.io/docs/camunda-cloud-console

I tried with Firefox 74.0 (64-bit) and Chrome 80.0.3987.163 (64-bit).
In both browsers nothing happens after clicking the related button. 
Btw: same is true for the top most menu item, which is showing my name (not sure whether this should show more info at all).

To reproduce:
    1. Open Camunda Cloud console
    2. Go to avatar menu
    3. Click on menu item '<your_name> Organizations'
    
Expected behavior
    A screen/dialog pops up showing a list of my organizations.

Observed behaviour
    Nothing happens

System information (please complete the following information as applicable):
    OS: Windows 10 Home 10.0.17763 (Build 17763
    Firefox 74.0 (64-bit) and Chrome 80.0.3987.163 (64-bit)

**Comment by afirth** [comment]
Hi @phileas74, thanks for reporting!
/cc @urbanisierung @ultraschuppi

**Comment by ultraschuppi** [comment]
Hi @phileas74 

yepp, there is no self-service organization-management built into console right now. We already work on plans to change that, but right now there is not other way than reaching out to Camunda to move multiple users into the same org

hth
 tim

**Comment by ultraschuppi** [comment]
@meyerdan i guess this is a feature-request, handing over to you therefor ;-)
